---
- name: Test play
  hosts: all

  tasks:

    - name: Touch a config file for demosite-static
      become: yes
      file:
        path: /etc/httpd/conf.d/01-demosite-static.conf
        state: touch

    - name: Touch a config file for demosite-php
      become: yes
      file:
        path: /etc/httpd/conf.d/01-demosite-php.conf
        state: touch

    - name: Insert config for demosite-static
      become: yes
      blockinfile:
        path: /etc/httpd/conf.d/01-demosite-static.conf
        block: |
          <VirtualHost *:80>
            ServerAdmin webmaster@localhost
            DocumentRoot /var/www/html/01-demosite-static
            DirectoryIndex index.html
          </VirtualHost>
    
    - name: Insert config for demosite-php
      become: yes
      blockinfile:
        path: /etc/httpd/conf.d/01-demosite-php.conf
        block: |
          <VirtualHost *:81>
            ServerAdmin webmaster@localhost
            DocumentRoot /var/www/html/01-demosite-php
            DirectoryIndex index.php
          </VirtualHost>

    - name: Add Apache port to listen
      become: yes
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        # regexp: '^Listen '
        insertafter: '^Listen '
        line: Listen 81

    - name: restart service httpd on centos
      become: yes
      systemd:
        state: restarted
        daemon_reload: yes
        name: httpd
        
