Vagrant.configure("2") do |config|
  config.vm.box = "pavelcoup/centos8"
  config.vm.hostname = "learning-devops"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081

  config.vm.synced_folder "../../task-01/sites", "/var/www/html", type: "rsync",
    rsync__exclude: ".git/"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", path: "script.sh"
end