Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.hostname = "learning-devops"

  # config.vm.network "public_network",
  #   use_dhcp_assigned_default_route: true

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081

  config.vm.synced_folder "../../task-01/sites", "/home/vagrant/sites", type: "rsync"

  config.vm.provision "shell", path: "script.sh"
end