Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.hostname = "learning-devops"

  config.vm.network "forwarded_port", guest: 8081, host: 80

  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = 'playbook.yaml'
    ansible.limit = 'all'
    ansible.install        = true
  end  
end