---
- name: Stop jenkins
  service: name=jenkins state=stopped

- name: Create directory.
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
  loop:
     - "{{ jenkins_home }}/jobs/BuildGo"
     - "{{ jenkins_ssl_key_path }}"

- name: configure plugins and jobs
  template:
    src: "{{ item.name }}"
    dest: "{{ item.path }}"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
    backup: yes
  loop:
    - { name: 'org.jenkinsci.plugins.golang.GolangBuildWrapper.xml', path: '{{ jenkins_home }}/org.jenkinsci.plugins.golang.GolangBuildWrapper.xml' }
    - { name: '{{ jenkins_ssl_key_file }}', path: '{{ jenkins_ssl_key_path }}{{ jenkins_ssl_key_file }}' }
    - { name: 'jenkins.plugins.publish_over_ssh.BapSshPublisherPlugin.xml.j2', path: '{{ jenkins_home }}/jenkins.plugins.publish_over_ssh.BapSshPublisherPlugin.xml' }
    - { name: 'credentials.xml', path: '{{ jenkins_home }}/credentials.xml' }
    - { name: 'master.key', path: '{{ jenkins_home }}/secrets/master.key' }
    - { name: 'hudson.util.Secret', path: '{{ jenkins_home }}/secrets/hudson.util.Secret' }
    - { name: 'config.xml.j2', path: '{{ jenkins_home }}/jobs/BuildGo/config.xml' }
  when: (role_path + '/templates/' + item.name) | is_file

- name: restart jenkins
  service: name=jenkins state=restarted

# - name: Remove old key.
#   file:
#     path: "{{ jenkins_ssl_key_path }}{{ jenkins_ssl_key_file }}"
#     state: absent

# - name: Remove old public key.
#   file:
#     path: "{{ jenkins_ssl_key_path }}{{ jenkins_ssl_key_file }}.pub"
#     state: absent

# - name: Create ssl keypair
#   command: >
#     sudo -u jenkins ssh-keygen -m PEM -b 4096 -t rsa -N "" -f {{ jenkins_ssl_key_path }}{{ jenkins_ssl_key_file }}

# - name: define ssl_public_key
#   command: >
#     sudo -u jenkins cat {{ jenkins_ssl_key_path }}{{ jenkins_ssl_key_file }}.pub
#   register: ssl_public_key

# - debug: msg="{{ ssl_public_key.stdout }}"
