Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "learning-devops"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081

  config.vm.synced_folder "../../task-01/sites", "/home/vagrant/sites", type: "rsync"

  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = 'main.yaml'
    ansible.limit = 'all'
    ansible.verbose        = true
    ansible.inventory_path = "./inventory/hosts"
  end

end
