version: '3'

services:
  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile-jenkins
    volumes:
      - ./jenkins_files/pipeline:/var/lib/jenkins/jobs/pipeline
      - ./jenkins_files/free:/var/lib/jenkins/jobs/free
      - ./jenkins_files/org.jenkinsci.plugins.golang.GolangBuildWrapper.xml:/var/lib/jenkins/org.jenkinsci.plugins.golang.GolangBuildWrapper.xml
      - ./jenkins_files/credentials.xml:/var/lib/jenkins/credentials.xml
      - ./jenkins_files/hudson.util.Secret:/var/lib/jenkins/secrets/hudson.util.Secret
      - ./jenkins_files/master.key:/var/lib/jenkins/secrets/master.key
    ports:
      - "80:8080"
  nexus:
    build:
      context: ./
      dockerfile: Dockerfile-nexus
