version: '3'

services:
  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile-jenkins
    volumes:
      - ./jenkins_files/pipeline:/var/lib/jenkins/jobs/pipeline
      - ./jenkins_files/free:/var/lib/jenkins/jobs/free
      - ./jenkins_files/org.jenkinsci.plugins.golang.GolangBuildWrapper.xml:/var/lib/jenkins/org.jenkinsci.plugins.golang.GolangBuildWrapper.xml
      - ./jenkins_files/credentials.xml:/var/lib/jenkins/credentials.xml
      - ./jenkins_files/hudson.util.Secret:/var/lib/jenkins/secrets/hudson.util.Secret
      - ./jenkins_files/master.key:/var/lib/jenkins/secrets/master.key
    ports:
      - "8080:8080"
  nexus:
    # image: sonatype/nexus3:3.20.1
    # user: root
    # volumes:
    #   - ./nexus_files:/scripts
    build:
      context: ./
      dockerfile: Dockerfile-nexus
    ports:
      - "8081:8081"