---
- name: Setup Jenkins
  hosts: jenkins
  become: yes
  vars:
    jenkins_hostname: localhost
    jenkins_plugins:
      - golang
      - git
      - github
      - nexus-artifact-uploader
      - publish-over-ssh
    jenkins_plugins_install_dependencies: true
  pre_tasks:
    - apt:
        pkg:
        - mc
        - nano
        - git
        - build-essential
        - jq
        state: present
  roles:
    - role: "/etc/ansible/roles/jenkins"

- name: Setup Nexus
  hosts: nexus
  become: yes
  vars:
    java_packages:
      - adoptopenjdk-8-hotspot-jre
    nexus_admin_password: admin
    nexus_repos_raw_hosted:
      - name: word-cloud-generator
        write_policy: ALLOW
        blob_store: default
        strict_content_validation: false
    nexus_roles:
      - id: word-cloud-generator-developpers
        name: word-cloud-generator-developpers
        description: ''
        privileges:
          - nx-repository-view-raw-word-cloud-generator-*
        roles: []
      - id: word-cloud-generator-reader
        name: word-cloud-generator-reader
        description: ''
        privileges:
          - nx-repository-view-raw-word-cloud-generator-read
        roles: []
    nexus_local_users:
      - username: jenkins
        first_name: Jenkins
        last_name: CI
        email: support@company.com
        password: "{{ nexus_staging_production_password }}"
        roles:
          - word-cloud-generator-developpers
      - username: staging_production
        first_name: staging_production
        last_name: CI
        email: support@company.com
        password: "{{ nexus_staging_production_password }}"
        roles:
          - word-cloud-generator-reader
  pre_tasks:
    - apt:
        name: gpg
        state: present
    - apt_key:
        url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    - apt_repository:
        repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main
        state: present
        update_cache: true
  roles:
    - role: "/etc/ansible/roles/java"
    - role: "/etc/ansible/roles/nexus3"

- name: Setup Word-Cloud-Generator
  hosts: staging_production
  become: yes
  roles:
    - role: "/etc/ansible/roles/systemd-service"
      systemd_service:
        wordcloud:
          enabled: yes
          exec_start: "/opt/wordcloud/word-cloud-generator"
          wanted_by: "multi-user.target"
  tasks:
    - file:
        path: /opt/wordcloud/
        state: directory
        mode: '0755'
        owner: vagrant

    - apt:
        name: curl
        state: present
